package koreader

import (
	"archive/zip"
	"encoding/json"
	"fmt"
	"io"
	"strings"
)

// BuildPlugin writes a ready-to-install plugin zip for one device: extract
// it and drop the resulting booky.koplugin folder into KOReader's plugins
// directory; it syncs against serverURL with the device's own token.
// Everything device-specific lives in the generated config.lua; the plugin
// code itself is static.
//
// The entries sit at the zip root on purpose: the download is served as
// booky.koplugin.zip, so the folder desktop extractors wrap the contents in
// is named booky.koplugin — the exact folder to copy. A folder inside the
// zip would come out nested one level deeper on Windows and most GUI tools.
func (s *Store) BuildPlugin(w io.Writer, d *Device, serverURL string) error {
	serverURL = strings.TrimRight(strings.TrimSpace(serverURL), "/")
	if serverURL == "" {
		return fmt.Errorf("set the server URL first — the plugin needs to know where Booky lives")
	}
	zw := zip.NewWriter(w)
	files := map[string]string{
		"_meta.lua":  metaLua,
		"main.lua":   mainLua,
		"config.lua": configLua(d, serverURL),
	}
	// deterministic order keeps zips byte-comparable for the same inputs
	for _, name := range []string{"_meta.lua", "main.lua", "config.lua"} {
		f, err := zw.Create(name)
		if err != nil {
			return err
		}
		if _, err := f.Write([]byte(files[name])); err != nil {
			return err
		}
	}
	return zw.Close()
}

// configLua renders the per-device settings. Values are emitted as Lua
// literals; the token and URL are hex/URL-safe by construction.
func configLua(d *Device, serverURL string) string {
	auto, _ := json.Marshal(d.AutoIDs) //nolint:errcheck // []int64 cannot fail
	libs, _ := json.Marshal(d.Libraries)
	return fmt.Sprintf(`-- Generated by Booky for device %q — do not edit; rebuild from
-- Settings → KoReader devices instead.
-- The download folder is chosen on-device (Booky → Download folder) and kept
-- in KOReader's own settings, so it survives plugin rebuilds.
return {
    server_url = %q,
    token = %q,
    device_name = %q,
    -- JSON arrays of library ids (decoded in main.lua)
    libraries = %q,
    auto_libraries = %q,
}
`, d.Name, serverURL, d.Token, d.Name, string(libs), string(auto))
}

const metaLua = `local _ = require("gettext")
return {
    name = "booky",
    fullname = _("Booky"),
    description = _([[Browse your Booky libraries (by author, series or genre), download books over wifi, and auto-sync new arrivals.]]),
}
`

// mainLua is the static plugin body. It keeps to stable KOReader APIs:
// a main-menu entry, NetworkMgr-gated sync, http requests via socket.http,
// Menu-widget lists for browsing, and per-book download tracking in a local
// LuaSettings file.
const mainLua = `local Blitbuffer = require("ffi/blitbuffer")
local Button = require("ui/widget/button")
local CenterContainer = require("ui/widget/container/centercontainer")
local ConfirmBox = require("ui/widget/confirmbox")
local DataStorage = require("datastorage")
local Dispatcher = require("dispatcher")
local Font = require("ui/font")
local FrameContainer = require("ui/widget/container/framecontainer")
local Geom = require("ui/geometry")
local GestureRange = require("ui/gesturerange")
local HorizontalGroup = require("ui/widget/horizontalgroup")
local ImageWidget = require("ui/widget/imagewidget")
local InfoMessage = require("ui/widget/infomessage")
local InputContainer = require("ui/widget/container/inputcontainer")
local LuaSettings = require("luasettings")
local Menu = require("ui/widget/menu")
local NetworkMgr = require("ui/network/manager")
local OverlapGroup = require("ui/widget/overlapgroup")
local RightContainer = require("ui/widget/container/rightcontainer")
local Screen = require("device").screen
local Size = require("ui/size")
local TextBoxWidget = require("ui/widget/textboxwidget")
local TextWidget = require("ui/widget/textwidget")
local TitleBar = require("ui/widget/titlebar")
local UIManager = require("ui/uimanager")
local VerticalGroup = require("ui/widget/verticalgroup")
local VerticalSpan = require("ui/widget/verticalspan")
local WidgetContainer = require("ui/widget/container/widgetcontainer")
local http = require("socket.http")
local json = require("json")
local lfs = require("libs/libkoreader-lfs")
local ltn12 = require("ltn12")
local socketutil = require("socketutil")
local _ = require("gettext")

local config = require("config")

local Booky = WidgetContainer:extend{
    name = "booky",
    is_doc_only = false,
}

function Booky:init()
    self.settings = LuaSettings:open(DataStorage:getSettingsDir() .. "/booky.lua")
    -- installs from before the folder was user-chosen downloaded into
    -- <data>/booky — adopt that folder so their existing books stay found
    if not self.settings:readSetting("download_dir") then
        local legacy = DataStorage:getFullDataDir() .. "/booky"
        if lfs.attributes(legacy, "mode") == "directory" then
            self.settings:saveSetting("download_dir", legacy)
            self.settings:flush()
        end
    end
    self.cover_cache = DataStorage:getFullDataDir() .. "/cache/booky-covers"
    self._cover_miss = {}
    self._menus = {}
    self:onDispatcherRegisterActions()
    self.ui.menu:registerToMainMenu(self)
    -- opportunistic auto-sync shortly after startup when wifi is already up
    UIManager:scheduleIn(10, function()
        if NetworkMgr:isOnline() then self:autoSync() end
    end)
end

-- ---- download folder ----

-- downloadRoot returns the user-chosen folder, or nil if none is set yet.
-- There is deliberately no default: KOReader homes differ per person, and a
-- wrong guess scatters books where the file manager never looks.
function Booky:downloadRoot()
    return self.settings:readSetting("download_dir")
end

function Booky:chooseDownloadDir(after)
    require("ui/downloadmgr"):new{
        onConfirm = function(path)
            self.settings:saveSetting("download_dir", path)
            self.settings:flush()
            if after then
                -- mid-download: that callback is about to fetch something, and
                -- an auto-sync alongside it would race the same files
                after()
            else
                -- Picking the folder from the menu is usually the LAST thing
                -- standing between a fresh install and its first auto-sync:
                -- the startup check has already been and gone, and wifi came
                -- up while there was still nowhere to put anything. Without
                -- this the next attempt is a reboot away.
                UIManager:scheduleIn(1, function() self:autoSync() end)
            end
        end,
    }:chooseDir(self:downloadRoot())
end

-- ensureDownloadDir runs then_cb only once a download folder exists,
-- prompting the user to pick one first if needed. Every download path goes
-- through here.
function Booky:ensureDownloadDir(then_cb)
    if self:downloadRoot() then
        then_cb()
        return
    end
    UIManager:show(ConfirmBox:new{
        text = _("Booky needs to know where to put downloaded books.\n\nPick the folder KOReader should store them in — usually your home folder."),
        ok_text = _("Choose folder"),
        ok_callback = function() self:chooseDownloadDir(then_cb) end,
    })
end

-- ---- view style ----

function Booky:viewStyle()
    return self.settings:readSetting("view_style") or "list"
end

function Booky:setViewStyle(style)
    self.settings:saveSetting("view_style", style)
    self.settings:flush()
end

function Booky:onDispatcherRegisterActions()
    Dispatcher:registerAction("booky_sync", {
        category = "none", event = "BookySync", title = _("Booky: sync all books"), general = true,
    })
    Dispatcher:registerAction("booky_browse", {
        category = "none", event = "BookyBrowse", title = _("Booky: browse library"), general = true,
    })
end

function Booky:addToMainMenu(menu_items)
    menu_items.booky = {
        text = _("Booky"),
        sorting_hint = "tools",
        sub_item_table = {
            {
                text = _("Browse library"),
                callback = function() self:browse() end,
            },
            {
                text = _("Sync all books"),
                callback = function() self:syncAll() end,
            },
            {
                text_func = function()
                    return _("Download folder: ") .. (self:downloadRoot() or _("not set"))
                end,
                callback = function() self:chooseDownloadDir() end,
            },
            {
                text = _("Browse style"),
                sub_item_table = {
                    {
                        text = _("List"),
                        radio = true,
                        checked_func = function() return self:viewStyle() == "list" end,
                        callback = function() self:setViewStyle("list") end,
                    },
                    {
                        text = _("Cover mosaic"),
                        radio = true,
                        checked_func = function() return self:viewStyle() == "mosaic" end,
                        callback = function() self:setViewStyle("mosaic") end,
                    },
                },
            },
            {
                text = _("About"),
                callback = function()
                    UIManager:show(InfoMessage:new{
                        text = _("Booky device: ") .. (config.device_name or "?")
                            .. "\n" .. _("Server: ") .. (config.server_url or "?")
                            .. "\n" .. _("Downloads: ") .. (self:downloadRoot() or _("not set"))
                            .. "\n\n" .. _("New arrivals from auto-download libraries sync on their own whenever wifi connects."),
                    })
                end,
            },
        },
    }
end

function Booky:onBookySync()
    self:syncAll()
    return true
end

function Booky:onBookyBrowse()
    self:browse()
    return true
end

-- request performs an authenticated GET; returns body or nil, err.
function Booky:request(path, sink_file)
    local url = config.server_url .. path
    local sink, chunks
    if sink_file then
        sink = ltn12.sink.file(io.open(sink_file, "w+b"))
    else
        chunks = {}
        sink = ltn12.sink.table(chunks)
    end
    socketutil:set_timeout(20, 60)
    local _r, code = http.request{
        url = url,
        headers = { ["Authorization"] = "Bearer " .. config.token },
        sink = sink,
    }
    socketutil:reset_timeout()
    if code ~= 200 then
        return nil, "HTTP " .. tostring(code)
    end
    if sink_file then return true end
    return table.concat(chunks)
end

-- fetchCatalog pulls the shelf list (every downloadable book in this
-- device's libraries) and decodes it.
function Booky:fetchCatalog()
    local body, err = self:request("/api/koreader/v1/sync")
    if not body then return nil, err end
    local ok, data = pcall(json.decode, body)
    if not ok or type(data) ~= "table" then return nil, _("bad response") end
    return data.books or {}
end

function Booky:bookKey(book)
    return tostring(book.id) .. ":" .. tostring(book.libraryId)
end

function Booky:bookDest(book)
    local root = self:downloadRoot()
    if not root then return nil end
    return root .. "/" .. book.filename
end

function Booky:isDownloaded(book)
    local dest = self:bookDest(book)
    return dest ~= nil and lfs.attributes(dest, "mode") == "file"
end

-- coverPath returns a local cover image for the book, fetching it from the
-- server once and caching it on device. nil when the server has no cover
-- (remembered per session, so the mosaic doesn't re-ask on every repaint).
function Booky:coverPath(book)
    local dest = self.cover_cache .. "/" .. tostring(book.id) .. ".jpg"
    if lfs.attributes(dest, "mode") == "file" then return dest end
    if self._cover_miss[self:bookKey(book)] then return nil end
    lfs.mkdir(self.cover_cache)
    local ok = self:request("/api/koreader/v1/cover/"
        .. tostring(book.libraryId) .. "/" .. tostring(book.id), dest)
    if not ok then
        os.remove(dest)
        self._cover_miss[self:bookKey(book)] = true
        return nil
    end
    return dest
end

function Booky:markDownloaded(book)
    local seen = self.settings:readSetting("downloaded") or {}
    seen[self:bookKey(book)] = true
    self.settings:saveSetting("downloaded", seen)
    self.settings:flush()
end

-- downloadOne fetches a single book file; returns true on success.
function Booky:downloadOne(book)
    local dest = self:bookDest(book)
    if not dest then return false end
    local okdl = self:request("/api/koreader/v1/download/"
        .. tostring(book.libraryId) .. "/" .. tostring(book.id), dest)
    if not okdl then
        os.remove(dest)
        return false
    end
    self:markDownloaded(book)
    return true
end

-- downloadBatch fetches several books back to back with a progress note,
-- then reports a summary. done_cb runs after (menus refresh through it).
function Booky:downloadBatch(books, done_cb)
    lfs.mkdir(self:downloadRoot())
    local info = InfoMessage:new{
        text = _("Booky: downloading ") .. tostring(#books) .. _(" book(s)…"),
    }
    UIManager:show(info)
    UIManager:forceRePaint()
    local fetched, failed = 0, 0
    for _i, b in ipairs(books) do
        if self:downloadOne(b) then fetched = fetched + 1 else failed = failed + 1 end
    end
    UIManager:close(info)
    local msg = _("Booky: ") .. tostring(fetched) .. _(" book(s) downloaded")
    if failed > 0 then msg = msg .. ", " .. tostring(failed) .. _(" failed") end
    UIManager:show(InfoMessage:new{ text = msg })
    if done_cb then done_cb() end
end

-- ---- browse ----

-- openList shows a full-screen Menu; items carry their own tap/hold
-- callbacks. Returns the menu so callers can refresh its items.
function Booky:openList(title, items)
    local menu
    menu = Menu:new{
        title = title,
        item_table = items,
        is_borderless = true,
        is_popout = false,
        covers_fullscreen = true,
        title_bar_fm_style = true,
        width = Screen:getWidth(),
        height = Screen:getHeight(),
        onMenuSelect = function(_m, item)
            if item.callback then item.callback() end
            return true
        end,
        onMenuHold = function(_m, item)
            if item.hold_callback then item.hold_callback() end
            return true
        end,
        close_callback = function()
            UIManager:close(menu)
            for i = #self._menus, 1, -1 do
                if self._menus[i] == menu then table.remove(self._menus, i) end
            end
        end,
    }
    table.insert(self._menus, menu)
    UIManager:show(menu)
    return menu
end

function Booky:closeMenus()
    for i = #self._menus, 1, -1 do
        UIManager:close(self._menus[i])
    end
    self._menus = {}
end

-- browse fetches the catalog and opens the filter menu: all books, or
-- narrowed by author / series / genre so nobody scrolls a whole library.
function Booky:browse()
    if not NetworkMgr:isOnline() then
        UIManager:show(InfoMessage:new{ text = _("Booky: no network connection") })
        return
    end
    local books, err = self:fetchCatalog()
    if not books then
        UIManager:show(InfoMessage:new{ text = _("Booky: ") .. tostring(err) })
        return
    end
    if #books == 0 then
        UIManager:show(InfoMessage:new{
            text = _("Booky: no downloadable files in this device's libraries yet"),
        })
        return
    end
    self._menus = {}

    local authors, series, genres = {}, {}, {}
    local function group(t, name, book)
        if name and name ~= "" then
            t[name] = t[name] or {}
            table.insert(t[name], book)
        end
    end
    for _i, b in ipairs(books) do
        group(authors, b.author, b)
        group(series, b.seriesName, b)
        for _j, g in ipairs(b.genres or {}) do group(genres, g, b) end
    end
    local function groupCount(t)
        local n = 0
        for _k in pairs(t) do n = n + 1 end
        return n
    end

    local root = {
        {
            text = _("All books"), mandatory = tostring(#books),
            callback = function() self:openBooks(_("All books"), books, false) end,
        },
        {
            text = _("By author"), mandatory = tostring(groupCount(authors)),
            callback = function() self:openGroup(_("Authors"), authors, false) end,
        },
        {
            text = _("By series"), mandatory = tostring(groupCount(series)),
            callback = function() self:openGroup(_("Series"), series, true) end,
        },
        {
            text = _("By genre"), mandatory = tostring(groupCount(genres)),
            callback = function() self:openGroup(_("Genres"), genres, false) end,
        },
    }
    self:openList(_("Booky library"), root)
end

-- openBooks routes a book collection to the user's chosen browse style.
function Booky:openBooks(title, books, series_order)
    local list = {}
    for _i, b in ipairs(books) do table.insert(list, b) end
    if series_order then
        table.sort(list, function(a, b)
            return (a.seriesNum or 0) < (b.seriesNum or 0)
        end)
    else
        table.sort(list, function(a, b)
            return (a.title or ""):lower() < (b.title or ""):lower()
        end)
    end
    if self:viewStyle() == "mosaic" then
        self:openBookGrid(title, list)
    else
        self:openBookList(title, list, series_order)
    end
end

-- confirmDownload double-checks a batch with the user, then runs it.
function Booky:confirmDownload(batch, done_cb)
    if #batch == 0 then
        UIManager:show(InfoMessage:new{ text = _("Booky: everything here is already on this device") })
        return
    end
    self:ensureDownloadDir(function()
        UIManager:show(ConfirmBox:new{
            text = _("Download ") .. tostring(#batch) .. _(" book(s) to this device?"),
            ok_text = _("Download"),
            ok_callback = function()
                UIManager:scheduleIn(0.1, function()
                    self:downloadBatch(batch, done_cb)
                end)
            end,
        })
    end)
end

-- openGroup lists group names (authors, series, genres) with book counts.
function Booky:openGroup(title, groups, series_order)
    local names = {}
    for name in pairs(groups) do table.insert(names, name) end
    table.sort(names, function(a, b) return a:lower() < b:lower() end)
    local items = {}
    for _i, name in ipairs(names) do
        local list = groups[name]
        table.insert(items, {
            text = name,
            mandatory = tostring(#list),
            callback = function() self:openBooks(name, list, series_order) end,
        })
    end
    self:openList(title, items)
end

-- openBookList lists books with multi-select batch downloads:
--   tap        download one book (or toggle, once a selection is active)
--   long-press start/extend a selection
--   first row  download everything selected — or everything missing
-- The list arrives pre-sorted from openBooks.
function Booky:openBookList(title, list, series_order)
    local selected = {} -- bookKey -> book
    local menu
    local refresh

    local function selectedBooks()
        local out = {}
        for _i, b in ipairs(list) do
            if selected[self:bookKey(b)] then table.insert(out, b) end
        end
        return out
    end
    local function missingBooks()
        local out = {}
        for _i, b in ipairs(list) do
            if not self:isDownloaded(b) then table.insert(out, b) end
        end
        return out
    end
    local function toggle(b)
        local key = self:bookKey(b)
        if selected[key] then selected[key] = nil else selected[key] = b end
        refresh()
    end
    local function confirmBatch(batch)
        self:confirmDownload(batch, function()
            selected = {}
            refresh()
        end)
    end

    local function buildItems()
        local items = {}
        local sel = selectedBooks()
        local action_text
        if #sel > 0 then
            action_text = _("Download selected") .. " (" .. tostring(#sel) .. ")"
        else
            action_text = _("Download all missing") .. " (" .. tostring(#missingBooks()) .. ")"
        end
        table.insert(items, {
            text = "↓ " .. action_text,
            bold = true,
            callback = function()
                if #sel > 0 then confirmBatch(sel) else confirmBatch(missingBooks()) end
            end,
        })
        local selecting = #sel > 0
        for _i, b in ipairs(list) do
            local text = b.title or "?"
            if series_order and b.seriesNum and b.seriesNum > 0 then
                text = string.format("%g · %s", b.seriesNum, text)
            elseif b.author and b.author ~= "" then
                text = text .. " — " .. b.author
            end
            if selecting then
                text = (selected[self:bookKey(b)] and "● " or "○ ") .. text
            end
            local mark = (b.format or ""):upper()
            if self:isDownloaded(b) then mark = "✓" end
            table.insert(items, {
                text = text,
                mandatory = mark,
                callback = function()
                    if selecting then toggle(b) else self:pickBook(b, refresh) end
                end,
                hold_callback = function() toggle(b) end,
            })
        end
        return items
    end

    refresh = function()
        menu:switchItemTable(nil, buildItems())
    end
    menu = self:openList(title, buildItems())
end

-- ---- cover mosaic ----

-- Covers in the mosaic get rounded corners. ImageWidget paints a bitmap and
-- can't clip it, and a FrameContainer radius would only round a border drawn
-- AROUND a still-square picture, so the corners are carved instead: paint the
-- image, then paint the four corner wedges back out in the page color. One
-- one-pixel-tall rect per row per corner, so a 10px radius costs 40 fills.
--
-- radius.window, not radius.default: default is 2px before DPI scaling and
-- vanishes on a cover this size, while window is the toolkit's visible
-- panel-corner rounding. nil (an older Size table) just leaves them square.
local COVER_RADIUS = Size.radius and Size.radius.window

local function carveRoundedCorners(bb, x, y, w, h, r)
    if not r or r < 1 then return end
    r = math.min(r, math.floor(math.min(w, h) / 2))
    for i = 0, r - 1 do
        -- how far the arc sits from the edge on this row, measured from the
        -- pixel's middle so the curve doesn't look a row short
        local dy = r - i - 0.5
        local dx = math.ceil(r - math.sqrt(r * r - dy * dy))
        if dx > 0 then
            bb:paintRect(x, y + i, dx, 1, Blitbuffer.COLOR_WHITE)
            bb:paintRect(x + w - dx, y + i, dx, 1, Blitbuffer.COLOR_WHITE)
            bb:paintRect(x, y + h - 1 - i, dx, 1, Blitbuffer.COLOR_WHITE)
            bb:paintRect(x + w - dx, y + h - 1 - i, dx, 1, Blitbuffer.COLOR_WHITE)
        end
    end
end

local RoundedCover = ImageWidget:extend{ radius = nil }

function RoundedCover:paintTo(bb, x, y)
    if self.hide then return end -- nothing was painted, so carve nothing
    ImageWidget.paintTo(self, bb, x, y)
    local size = self:getSize()
    carveRoundedCorners(bb, x, y, size.w, size.h, self.radius)
end

-- CoverCell is one tappable tile in the mosaic: a bare cover (or title
-- placeholder), tap/hold callbacks wired by the grid.
local CoverCell = InputContainer:extend{
    width = nil, height = nil, content = nil,
    on_tap = nil, on_hold = nil,
}

function CoverCell:init()
    self.dimen = Geom:new{ w = self.width, h = self.height }
    self.ges_events = {
        TapCell = { GestureRange:new{ ges = "tap", range = function() return self.dimen end } },
        HoldCell = { GestureRange:new{ ges = "hold", range = function() return self.dimen end } },
    }
    self[1] = self.content
end

function CoverCell:onTapCell()
    if self.on_tap then self.on_tap() end
    return true
end

function CoverCell:onHoldCell()
    if self.on_hold then self.on_hold() end
    return true
end

-- BookyMosaic is the paginated cover-grid browse view. Same interactions as
-- the list: tap downloads/opens (or toggles once a selection is active),
-- long-press selects, the bottom action button batches. Swipe to page.
local BookyMosaic = InputContainer:extend{
    plugin = nil, title = nil, books = nil,
    covers_fullscreen = true,
}

function BookyMosaic:init()
    self.dimen = Geom:new{ x = 0, y = 0, w = Screen:getWidth(), h = Screen:getHeight() }
    self.page = 1
    self.selected = {}
    self.ges_events = {
        PageSwipe = { GestureRange:new{ ges = "swipe", range = function() return self.dimen end } },
    }
    self:refresh()
end

function BookyMosaic:paintTo(bb, x, y)
    bb:paintRect(x, y, self.dimen.w, self.dimen.h, Blitbuffer.COLOR_WHITE)
    InputContainer.paintTo(self, bb, x, y)
end

function BookyMosaic:onCloseWidget()
    local menus = self.plugin._menus
    for i = #menus, 1, -1 do
        if menus[i] == self then table.remove(menus, i) end
    end
end

function BookyMosaic:onPageSwipe(_arg, ges)
    if ges.direction == "west" then
        self:goPage(self.page + 1)
    elseif ges.direction == "east" then
        self:goPage(self.page - 1)
    end
    return true
end

function BookyMosaic:goPage(p)
    if p < 1 or p > (self.pages or 1) or p == self.page then return end
    self.page = p
    self:refresh()
end

function BookyMosaic:selectedBooks()
    local out = {}
    for _i, b in ipairs(self.books) do
        if self.selected[self.plugin:bookKey(b)] then table.insert(out, b) end
    end
    return out
end

function BookyMosaic:missingBooks()
    local out = {}
    for _i, b in ipairs(self.books) do
        if not self.plugin:isDownloaded(b) then table.insert(out, b) end
    end
    return out
end

function BookyMosaic:toggle(b)
    local key = self.plugin:bookKey(b)
    if self.selected[key] then self.selected[key] = nil else self.selected[key] = b end
    self:refresh()
end

function BookyMosaic:cellFor(b, cell_w, cell_h, cover_w, cover_h)
    local p = self.plugin
    local key = p:bookKey(b)
    local inner
    local cover = p:coverPath(b)
    if cover then
        -- the cover floats bare on the page — no card, no caption
        inner = RoundedCover:new{ file = cover, width = cover_w, height = cover_h, scale_factor = 0, radius = COVER_RADIUS }
    else
        -- no cover on the server: a bordered title tile stands in for one,
        -- rounded to match the real covers beside it
        inner = FrameContainer:new{
            bordersize = Size.border.thin,
            radius = COVER_RADIUS,
            padding = 0,
            CenterContainer:new{
                dimen = Geom:new{ w = cover_w - Size.border.thin * 2, h = cover_h - Size.border.thin * 2 },
                TextBoxWidget:new{
                    text = b.title or "?",
                    width = cover_w - Size.padding.default * 2,
                    alignment = "center",
                    face = Font:getFace("smallinfofont"),
                },
            },
        }
    end
    -- state lives in a small corner badge instead of a caption line:
    -- ●/○ while a selection is active, ✓ when the book is on the device
    local badge_text
    if next(self.selected) then
        badge_text = self.selected[key] and "●" or "○"
    elseif p:isDownloaded(b) then
        badge_text = "✓"
    end
    local content = inner
    if badge_text then
        local badge = FrameContainer:new{
            background = Blitbuffer.COLOR_WHITE,
            bordersize = Size.border.thin,
            padding = Size.padding.tiny,
            TextWidget:new{ text = badge_text, face = Font:getFace("infofont", 14) },
        }
        content = OverlapGroup:new{
            dimen = Geom:new{ w = cover_w, h = cover_h },
            inner,
            RightContainer:new{ dimen = Geom:new{ w = cover_w, h = badge:getSize().h }, badge },
        }
    end
    if self.selected[key] then
        content = FrameContainer:new{ bordersize = Size.border.thick, radius = COVER_RADIUS, padding = 0, content }
    end
    return CoverCell:new{
        width = cell_w,
        height = cell_h,
        content = CenterContainer:new{ dimen = Geom:new{ w = cell_w, h = cell_h }, content },
        on_tap = function()
            if next(self.selected) then
                self:toggle(b)
            else
                p:pickBook(b, function() self:refresh() end)
            end
        end,
        on_hold = function() self:toggle(b) end,
    }
end

function BookyMosaic:refresh()
    local titlebar = TitleBar:new{
        title = self.title,
        with_bottom_line = true,
        close_callback = function() UIManager:close(self) end,
        show_parent = self,
    }
    local cols = Screen:getWidth() > Screen:getHeight() and 4 or 3
    local cell_w = math.floor(Screen:getWidth() / cols)
    local pad = Size.padding.default * 2
    local cover_w = cell_w - pad
    local cover_h = math.floor(cover_w * 3 / 2)
    local cell_h = cover_h + pad

    local sel = self:selectedBooks()
    local action_text
    if #sel > 0 then
        action_text = _("Download selected") .. " (" .. tostring(#sel) .. ")"
    else
        action_text = _("Download all missing") .. " (" .. tostring(#self:missingBooks()) .. ")"
    end
    local action = Button:new{
        text = "↓ " .. action_text,
        callback = function()
            local batch = #sel > 0 and sel or self:missingBooks()
            self.plugin:confirmDownload(batch, function()
                self.selected = {}
                self:refresh()
            end)
        end,
        show_parent = self,
    }
    local avail_h = Screen:getHeight() - titlebar:getHeight() - action:getSize().h - Size.padding.large * 2
    local rows = math.max(1, math.floor(avail_h / cell_h))
    local per_page = cols * rows
    self.pages = math.max(1, math.ceil(#self.books / per_page))
    if self.page > self.pages then self.page = self.pages end

    -- pages turn by swipe alone; the label just says where you are
    local page_label = TextWidget:new{
        text = " " .. tostring(self.page) .. " / " .. tostring(self.pages) .. " ",
        face = Font:getFace("infofont", 14),
    }

    local grid = VerticalGroup:new{ align = "left" }
    local first = (self.page - 1) * per_page + 1
    for r = 0, rows - 1 do
        local row = HorizontalGroup:new{ align = "top" }
        local any = false
        for c = 0, cols - 1 do
            local b = self.books[first + r * cols + c]
            if b then
                any = true
                table.insert(row, self:cellFor(b, cell_w, cell_h, cover_w, cover_h))
            end
        end
        if any then
            table.insert(grid, CenterContainer:new{
                dimen = Geom:new{ w = Screen:getWidth(), h = cell_h }, row,
            })
        end
    end

    local bottom = CenterContainer:new{
        dimen = Geom:new{ w = Screen:getWidth(), h = action:getSize().h + Size.padding.large },
        HorizontalGroup:new{ align = "center", page_label, action },
    }
    local used = titlebar:getHeight() + grid:getSize().h + bottom:getSize().h
    self[1] = VerticalGroup:new{
        align = "left",
        titlebar,
        grid,
        VerticalSpan:new{ width = math.max(0, Screen:getHeight() - used) },
        bottom,
    }
    UIManager:setDirty(self, "ui")
end

-- openBookGrid shows the mosaic for a pre-sorted book list.
function Booky:openBookGrid(title, list)
    local mosaic = BookyMosaic:new{
        plugin = self, title = title, books = list,
    }
    table.insert(self._menus, mosaic)
    UIManager:show(mosaic)
end

-- pickBook downloads (or offers to open) the tapped book.
function Booky:pickBook(book, on_change)
    if self:isDownloaded(book) then
        UIManager:show(ConfirmBox:new{
            text = _("Already on this device:\n") .. (book.title or "?") .. "\n\n" .. _("Open it now?"),
            ok_text = _("Open"),
            ok_callback = function() self:openBook(self:bookDest(book)) end,
        })
        return
    end
    self:ensureDownloadDir(function()
        UIManager:show(ConfirmBox:new{
            text = _("Download to this device?\n") .. (book.title or "?"),
            ok_text = _("Download"),
            ok_callback = function()
                UIManager:scheduleIn(0.1, function()
                    lfs.mkdir(self:downloadRoot())
                    if self:downloadOne(book) then
                        if on_change then on_change() end
                        UIManager:show(ConfirmBox:new{
                            text = _("Downloaded: ") .. (book.title or "?") .. "\n\n" .. _("Open it now?"),
                            ok_text = _("Open"),
                            ok_callback = function() self:openBook(self:bookDest(book)) end,
                        })
                    else
                        UIManager:show(InfoMessage:new{ text = _("Booky: download failed: ") .. (book.title or "?") })
                    end
                end)
            end,
        })
    end)
end

function Booky:openBook(path)
    self:closeMenus()
    local ReaderUI = require("apps/reader/readerui")
    ReaderUI:showReader(path)
end

-- ---- sync ----

-- syncAll (the manual "Sync all books" action) downloads EVERY book in the
-- device's libraries that isn't on the device yet — auto-download flags
-- don't matter here, they only govern the background sync. A count confirm
-- guards against surprise multi-hundred-book pulls.
function Booky:syncAll()
    if not NetworkMgr:isOnline() then
        UIManager:show(InfoMessage:new{ text = _("Booky: no network connection") })
        return
    end
    self:ensureDownloadDir(function() self:runSyncAll() end)
end

function Booky:runSyncAll()
    local books, err = self:fetchCatalog()
    if not books then
        UIManager:show(InfoMessage:new{ text = _("Booky sync failed: ") .. tostring(err) })
        return
    end
    local missing = {}
    for _i, b in ipairs(books) do
        if not self:isDownloaded(b) then table.insert(missing, b) end
    end
    if #missing == 0 then
        UIManager:show(InfoMessage:new{
            text = _("Booky: all ") .. tostring(#books) .. _(" book(s) are already on this device"),
        })
        return
    end
    UIManager:show(ConfirmBox:new{
        text = _("Download ") .. tostring(#missing) .. _(" of ") .. tostring(#books)
            .. _(" book(s) to this device?"),
        ok_text = _("Download"),
        ok_callback = function()
            UIManager:scheduleIn(0.1, function() self:downloadBatch(missing) end)
        end,
    })
end

-- autoSync runs silently in the background (wifi-connect and startup):
-- new arrivals from the auto-download libraries only. Already-downloaded
-- book ids are remembered locally, so deleting a file on-device doesn't
-- re-download it forever.
function Booky:autoSync()
    if not NetworkMgr:isOnline() then return end
    -- never guess a folder in the background: auto-sync waits until the user
    -- has picked one (Booky → Download folder)
    local root = self:downloadRoot()
    if not root then return end
    local books = self:fetchCatalog()
    if not books then return end

    local auto = {}
    for _i, id in ipairs(json.decode(config.auto_libraries or "[]")) do auto[id] = true end
    local seen = self.settings:readSetting("downloaded") or {}
    lfs.mkdir(root)

    for _i, book in ipairs(books) do
        if auto[book.libraryId] and not seen[self:bookKey(book)] then
            self:downloadOne(book)
        end
    end
end

-- opportunistic check-in whenever wifi comes up
function Booky:onNetworkConnected()
    UIManager:scheduleIn(5, function() self:autoSync() end)
end

-- ...and whenever the device wakes, which is when people actually expect new
-- books to be waiting. The delay gives wifi a moment to come back first.
--
-- This stays silent when there's no network: autoSync's first act is an
-- isOnline() check that returns without a word. Reading somewhere with no
-- internet costs nothing and says nothing — a popup on every wake would be
-- worse than the missing books.
function Booky:onResume()
    UIManager:scheduleIn(5, function() self:autoSync() end)
end

return Booky
`
